### PR TITLE
update buildah-in-container

### PR DESCRIPTION
**Pull request by sallyom**
update security demo

1) remove net=host, storage-driver=vfs to buildah cmds
2) switch alpine image to ubi8-minimal image
3) use buildah/stable for buildah

### CODE REVIEW

**Comment by vrothberg** [comment]
Hi @sallyom :wave: Could you sign the commit and add a description to it why the change is necessary?

**Comment by sallyom** [comment]
@vrothberg I'm going to update further, so I'll hold this for now : )

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
