### PR TITLE
QM demo viewer

### PR DESCRIPTION
**Pull request by Yarboa**
Fixing demo App to work with qm demo/devconf-2024

The following demo
Contains, mp4. video and python script to interact with HOST & QM
containers,

The video simulate the driving cockpit, and telltales of Host and QM processes
Change their state based on systemctl services status

### CODE REVIEW

**Comment by rhatdan** [comment]
Is this still a draft?

**Comment by Yarboa** [comment]
@dougsland
Can I upload the video you shared?

**Comment by dougsland** [comment]
> @dougsland Can I upload the video you shared?

Yes, that's me behind the wheel of my family car (GMC Yukon XL 2022) while performing some tests for the simulator we discussed.

**Comment by Yarboa** [comment]
> Is this still a draft?

@rhatdan ready

**Pull request merged**
