### PR TITLE
add podman_go_bindings demo

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@rhatdan @vrothberg @TomSweeneyRedHat PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
once this is merged I can update the blog post

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL

**Comment by lsm5** [comment]
i'll add a couple more things...

**Comment by lsm5** [comment]
changed context variable name and added busybox image pull example as well.

**Comment by lsm5** [comment]
good to go from my side..

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
