### PR TITLE
Make Buildah Intro be one file

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Thanks to @ipbabble, the buildah_intro.sh is now all
inclusive and the python file, bash script, and Dockerfile
are now all created within it.  Creating the PR per @ipbabble's
request.

### CODE REVIEW

**Comment by ipbabble** [comment]
LGTM

**Comment by ipbabble** [comment]
Reason for doing this is that for blogs, articles, and emailing, it makes sense to just need one script file. “Here Dan, use this at your next demo. See attached.” :-)

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
